### ISSUE TITLE
install

### ISSUE THREAD

**Issue by stefhenry** [Offerel/roundcube_primitivenotes#15]
Hi,

I am trying to install the plugin with RC 1.2.3

I get these kind of errors:
[21-Mar-2019 21:37:00 -0400]: DB Error: Configuration error. Unsupported database driver:  in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 84 (GET /rc/plugins/primitivenotes/notes.php)

As you can see the driver contains nothing, but in my config it is set to 'sqlite'. if I force this variable to 'sqlite' then I won't get this error message but the module is unusable.

My questions:
- does this module work with sqlite3?
- is it compatible with Roundcube Webmail 1.2.3 ?

Many thanks for your support!

**Comment by Offerel** [comment]
It seems, that this isn't a issue of the plugin itself. The message comes from the db driver in Roundcube and not from the plugin. I only use the functions provided by the base package. Since RC 1.2.3 is really outdated  version and the plugin is developed for at least RC 1.3.x, there can be problem with such old RC versions. I know that several functions of RC have changed over time and are deprecated or do not exist in the older versions of RC.

I have tested the plugin with SQlite and RC 1.3.x and 1.4 RC1 and didn't find any error messages so far. So my recommendation would be to upgrade RC to at least the last stable version. Currently this is 1.3.8. You can test also 1.4 RC1, but i wouldn't do this in a production environment.
