### ISSUE TITLE
Protect direct access

### ISSUE THREAD

**Issue by mvldebian** [Offerel/roundcube_primitivenotes#24]
How to protect direct access to files? using the full url they are accessed without password request ...

**Comment by Offerel** [comment]
I have no idea what you mean with direct access. If this files are directly accessible via browser, than something is miss-configured at your server. Normally such files shouldn't be accessible directly under webroot. Its up to the admin of the server to protect and serve the files.

**Comment by mvldebian** [comment]
I believe that by default in debian the directories and files are accessible by url, the directories I have disabled by a2dismod autoindex directive

But the files are still accessible by url
I bypassed by creating a .htaccess in the root where the plugin files will be saved with the content:

Order deny, allow
Deny from all

**Comment by Offerel** [comment]
Sorry, it seems I miss all the notifications since December from GitHub. Wasn't aware of a reply. I never used Apache as webserver and I know no one which used that anymore in production environment. But this should be the same for all webservers. As long as as you didn't store such files under webroot/docroot directory, no files are accessible by url. I mean there is no reason to store such files inside docroot. You should always store such files outside. For additional security I would recommend using open_basedir in php.ini

Please refer in php documentation for instructions.
