### ISSUE TITLE
Not working with 1.4.X version

### ISSUE THREAD

**Issue by bsbudhwar** [Offerel/roundcube_primitivenotes#28]
Hi its not working with latest stab;e version of 1.4.x and it should have the option to save the notes into Notes folder in mail tree folders like Inbox, Sent, Spam like Notes.

**Comment by Offerel** [comment]
Please check your log files. Its working with current stable RC release 1.4.x. 

The thing you mentioned would be a new feature which isn't possible the way you described it. Only in some rare cases its possible to save notes or files in this case in an IMAP structure. Since this are only some special setups where this is possible, I don't want to support such a feature. But feel free to fork my plugin and try it yourself.
