### ISSUE TITLE
Primitivenotes failed to load

### ISSUE THREAD

**Issue by wawefr** [Offerel/roundcube_primitivenotes#29]
Hello 
I have this error in the log
I'm on debian 9 and Roundcube 1-5 Git 
Thanks for your hep
Fred 

PHP Error: Failed to load plugin file /var/lib/roundcube/plugins/primitivenotes/primitivenotes.php in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 173 (POST /?_task=mail&_action=refresh)

**Comment by Offerel** [comment]
The latest Roundcube version i could found is 1.4.8. Can you please check with the latest official release? You should also check, if the plugin is installed in the correct directory. If the error persist, i need more information's and logfiles, specially whats you paths to roundcube, the plugins, logfiles from roundcube, your webserver and maybe some more php logfiles.

**Comment by wawefr** [comment]
Hello, thank you for your feedback.
You can fin the last version https://github.com/roundcube/roundcubemail.
It's difficult for me to downgrade my version to 1.4.
I check my configuration and I don't see something strange.
If you can help me, thanks 
Fred

**Comment by Offerel** [comment]
Please use only the latest released version, which is currently 1.4.8 (https://github.com/roundcube/roundcubemail/releases). At least with this version the plugin works fine. If you need support for installing Roundcube, please ask the Roundcube support team, this is out of the scope for this plugin. If you have the same issue with 1.4.8 you should provide me with the requested information's. I cant help without that.

**Comment by wawefr** [comment]
I am using the latest version 1.4.8 of Github (I checked).
I have checked the settings and the installation, everything is fine (I have other plugins that are ok)
Thank you for your help

**Comment by Offerel** [comment]
OK, since you are now on RC 1.4.8 and everything is fine, i assume, we can close this issue.

**Comment by wawefr** [comment]
Hello 
sorry I misspoke
when I say it's "fine" , it's my configuration that's ok but the plugin doesn't always work the same error
Thanks for your help

**Comment by Offerel** [comment]
OK, in this case please send me the log files i mentioned above, so that I can understand where the plugin fails.

**Comment by wawefr** [comment]
Hello
Thank you for your help
I share a log fil from roundcube 
[log.docx](https://github.com/Offerel/roundcube_primitivenotes/files/5187020/log.docx)

**Comment by Offerel** [comment]
I assume that the attached file is php error log? If thats the case i would recommend that you check your configuration files for roundcube. It seems something is not configured correctly. Either with in roundcube directly or with some of the plugins. Maybe the plugin before it loads primitivenotes. 

If that's all checked and correct, check if you are really using a final release and not the development version from a GitHub checkout.

If this is the case and you are using a final release version, you can open a bug report in roundcube, since it seems to be a bug in roundcube itself. I cant believe that, because im running Roundcube final release without any problem. All plugins, including primitivenotes are working fine.

**Comment by wawefr** [comment]
Hello
I checked my configuration and effectively It was a problem of installation, plugin are in many directory
All work fine now, very thanks for your help and sorry
Have a good day
