### ISSUE TITLE
Layout suggestions

### ISSUE THREAD

**Issue by mvldebian** [Offerel/roundcube_primitivenotes#30]
Hello
I would like to request two improvements to the layout.
The first would be the search bar that in the Elastic template the text field ends up leaving the space allocated in the template.

![image](https://user-images.githubusercontent.com/25337130/92308532-9f88aa00-ef74-11ea-9379-187859731576.png)

The second would be to provide a button to save the note during its creation

![image](https://user-images.githubusercontent.com/25337130/92308557-dbbc0a80-ef74-11ea-8590-1a08becb5830.png)

Thanks

**Comment by Offerel** [comment]
Many thx for the suggestions. I have tested the search box in Firefox and Chromium and i cant confirm. Your Screenshot. Can you please tell me which browser you are using?
![Firefox](https://user-images.githubusercontent.com/14041522/92333260-79522f80-f084-11ea-8357-370296dfcaa6.png)
![Chromium](https://user-images.githubusercontent.com/14041522/92333277-8c64ff80-f084-11ea-89e6-eeedfce5b3fe.png)

As for the save button: There is a Save Button in the toolbar:
![Markdown](https://user-images.githubusercontent.com/14041522/92333309-be766180-f084-11ea-96fa-b6b206130fa1.png)
![HTML](https://user-images.githubusercontent.com/14041522/92333322-d0f09b00-f084-11ea-9be5-80548ae437ef.png)

**Comment by mvldebian** [comment]
It occurs in both firefox and chrome, both on Linux.
The toolbar is also not displayed.
So I miss the save button when creating or editing.

![image](https://user-images.githubusercontent.com/25337130/92335447-5d8f5f00-f06d-11ea-8d0f-f625690c210d.png)

**Comment by Offerel** [comment]
It seems that in Linux there is some offset in pixel placement. Since im currently have no desktop Linux available to test, I can only try to fix that blindly. Only for some knowledge: what's your desktop environment? Gnome? KDE? Or something other?

According to your screen, it seems you are using txt files. There should be also some button to save the current file. Haven't used that since a long time now, but I will try to reproduce the issue tomorrow.

Only to not miss something, can you please have a look in Firefox developer console and look for plugin specific error messages? Should be F12 on the keyboard in every browser.

**Comment by mvldebian** [comment]
On Chrome console show this errors

![image](https://user-images.githubusercontent.com/25337130/92339112-d2bd5d00-f08a-11ea-8b69-0bddc353cd7c.png)

**Comment by mvldebian** [comment]
About Linux..

Linux Mint 20
Mate Desktop
Chrome and Firefox , updated

**Comment by mvldebian** [comment]
Other CSS error on console

DevTools failed to load SourceMap: Could not load content for https://roundcube.eth1.com.br/program/js/tinymce/skins/lightgray/skin.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Offerel** [comment]
Hi there,

The Searchbox I built seemingly quite dilettantish. I have now adapted the CSS and simplified it. 

When creating a new note, I changed the code to use the default format. Since there is only one default textarea for txt files, without an additional editor, I show a save button right of the note name.

I uploaded both changes in the Dev branch. Can you please check if this is OK for you? If yes, I will create a new version in the master branch.

**Comment by mvldebian** [comment]
With the version that is in the dev everything was ok.
Now, in a new note, the save button appears.
But I realized that using the MD extension is better and even the toolbar for editing loads. I will adopt but still on clients they exchange txt anyway.

Grateful for the help
