### ISSUE TITLE
default configuration reset

### ISSUE THREAD

**Issue by jeanneexarc** [Offerel/roundcube_primitivenotes#5]
Hello, is it normal that update to the new version with "compose update" rewrite configuration file ./plugins/primitivenotes/config.inc.php ? That mean I have to add notes_basepath manually after each update again.

**Comment by Offerel** [comment]
hi there. i have never used composer, so i dont know. but personally, i think this could be bug. since config.inc.php isn't directly part my package (only config.inc.php.dist is available), i would assume that a update mechanism do not touch such a file, which isnt part of the package. 

I try to ask in the roundcube forum. maybe they can tell me, if i could do anything.

**Comment by Offerel** [comment]
Since there was no response as of yet, i close that issue for now.
